FROM quay.io/konflux-ci/buildah-task:latest@sha256:4d8273444b0f2781264c232e12e88449bbf078c99e3da2a7f6dcaaf27bc53712

WORKDIR /opt/app-root/src

# We need multiple OPM versions because IIB uses different upstream versions for different OCP versions
ARG OPM_VERSION_1_26_4=v1.26.4
ARG OPM_VERSION_1_40_0=v1.40.0
ARG OPM_VERSION_1_44_0=v1.44.0
ARG OPM_VERSION_1_48_0=v1.48.0
ARG ORAS_VERSION="1.2.3"

RUN microdnf -y --setopt=tsflags=nodocs --setopt=install_weak_deps=0 install \
    findutils \
    gzip \
    jq \
    tar \
    python3 \
    python3-pip \
    skopeo \
    git \
    python3-file-magic && \
    microdnf clean all

# Install Python dependencies
RUN pip3 install --no-cache-dir \
    tenacity \
    GitPython \
    kubernetes \
    ruamel.yaml

# Install OPM versions
RUN curl -s -L https://github.com/operator-framework/operator-registry/releases/download/"${OPM_VERSION_1_26_4}"/linux-amd64-opm > /usr/bin/opm-"${OPM_VERSION_1_26_4}" && \
    curl -s -L https://github.com/operator-framework/operator-registry/releases/download/"${OPM_VERSION_1_40_0}"/linux-amd64-opm > /usr/bin/opm-"${OPM_VERSION_1_40_0}" && \
    curl -s -L https://github.com/operator-framework/operator-registry/releases/download/"${OPM_VERSION_1_44_0}"/linux-amd64-opm > /usr/bin/opm-"${OPM_VERSION_1_44_0}" && \
    curl -s -L https://github.com/operator-framework/operator-registry/releases/download/"${OPM_VERSION_1_48_0}"/linux-amd64-opm > /usr/bin/opm-"${OPM_VERSION_1_48_0}" && \
    curl -s -L -o oras.tar.gz https://github.com/oras-project/oras/releases/download/v"${ORAS_VERSION}"/oras_"${ORAS_VERSION}"_linux_amd64.tar.gz && \
    tar -xzf oras.tar.gz && rm oras.tar.gz && ls -la  && mv oras /usr/bin/oras && chmod +x /usr/bin/oras && \
    chmod +x /usr/bin/opm-*

# Copy the multi-arch builder script
COPY task/iib-image-builder-oci-ta/multi-arch-builder.py /usr/local/bin/multi-arch-builder.py
RUN chmod +x /usr/local/bin/multi-arch-builder.py

ENTRYPOINT ["/usr/bin/bash"]
